[[headers]]
for = "/*"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding"
Access-Control-Max-Age = "604800"
Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
Access-Control-Allow-Origin = "https://simulhost.com, https://www.simulhost.com"
Content-Security-Policy = "default-src 'none'; sandbox"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=86400, max-stale=3600, stale-while-revalidate=1800, stale-if-error=3600"
Origin-Cache-Control = "public, max-age=86400"
