[[headers]]
for = "/"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding, Etag"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=600, must-revalidate"
Origin-Cache-Control = "public, max-age=600, must-revalidate"

[[headers]]
for = "/index"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding, Etag"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=600, must-revalidate"
Origin-Cache-Control = "public, max-age=600, must-revalidate"
Link = '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">,     <link rel="icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon-precomposed" href="favicon.ico" type="image/x-icon">'

[[headers]]
for = "/index.html"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding, Etag"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=600, must-revalidate, proxy-revalidate"
Origin-Cache-Control = "public, max-age=600, must-revalidate, proxy-revalidate"
Link = '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">,     <link rel="icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon-precomposed" href="favicon.ico" type="image/x-icon">'

[[headers]]
for = "/favicon.png"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=63072000"
Origin-Cache-Control = "public, max-age=63072000"
Link = '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">,     <link rel="icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon-precomposed" href="favicon.ico" type="image/x-icon">'

[[headers]]
for = "/favicon.ico"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=63072000"
Origin-Cache-Control = "public, max-age=63072000"
Link = '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">,     <link rel="icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon-precomposed" href="favicon.ico" type="image/x-icon">'

[[headers]]
for = "/redirect"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=63072000"
Origin-Cache-Control = "public, max-age=63072000"
Link = '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">,     <link rel="icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon-precomposed" href="favicon.ico" type="image/x-icon">'


[[headers]]
for = "/redirect.txt"
[headers.values]
Alt-Svc = 'h2=":443"; ma=63072000; persist=1'
Alternate-Protocol = "443:npn-http/2"
Accept-Ranges = "bytes"
Vary = "Accept-Encoding, Content-Encoding"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Cache-Control = "public, max-age=63072000"
Origin-Cache-Control = "public, max-age=63072000"
Link = '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">,     <link rel="icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon" href="favicon.ico" type="image/x-icon">,     <link rel="apple-touch-icon-precomposed" href="favicon.ico" type="image/x-icon">'


[[redirects]]
from = "/redirect.txt"
to = "https://www.simulhost.com/"
status = 302
force = true

[[redirects]]
from = "/redirect"
to = "https://www.simulhost.com/"
status = 302
force = true

[[redirects]]
from = "http://simulhost.netlify.app/*"
to = "/redirect.txt"
status = 301
force = true

[[redirects]]
from = "https://simulhost.netlify.app/*"
to = "/redirect.txt"
status = 301
force = true

[[redirects]]
from = "http://simulhost.com/*"
to = "/redirect.txt"
status = 301
force = true

[[redirects]]
from = "https://simulhost.com/*"
to = "/redirect.txt"
status = 301
force = true
